### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by TejaRamachandran** [clairmont32/VirusTotal-IP-Scanner#2]
@clairmont32 
I am using your concept in my script to contextualize the IP for SIEM platforms.   

But I don't know why i am getting error for this IP "82.196.3.245". I think the issue with the JSON response from the server. 
```
>>> url = 'http://www.virustotal.com/vtapi/v2/ip-address/report'
>>> parameters = {'ip':'82.196.3.245', 'apikey': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
>>> response = urllib2.urlopen('%s?%s' % (url, urllib.urlencode(parameters))).read()
>>> r_dict = json.loads(response)

Traceback (most recent call last):
  File "<pyshell#83>", line 1, in <module>
    r_dict = json.loads(response)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by clairmont32** [comment]
Hmmm looks like it might not have had a response from VT. My code didn't
have exception handling built in, try putting the initial scan in a try:
except: statement and look for a response code of 1 upon initial scanning.

**Comment by TejaRamachandran** [comment]
Thanks @clairmont32. I will try that and update you

**Comment by clairmont32** [comment]
It also looks like there might be 1 too many parentheses in your response
string substitution. Double check for me as a sanity check for me lol

**Comment by TejaRamachandran** [comment]
yeah sure. @clairmont32 i didn't change anything in code, suddenly its started working man. Its Strange!!! 

```
>>> url = 'http://www.virustotal.com/vtapi/v2/ip-address/report'
>>> parameters = {'ip':'82.196.3.245', 'apikey': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
>>> response = urllib2.urlopen('%s?%s' % (url, urllib.urlencode(parameters))).read()
>>> r_dict = json.loads(response)
>>> print r_dict
{u'country': u'NL', u'response_code': 1, u'as_owner': u'ServerStack, Inc.', u'verbose_msg': u'IP address in dataset', u'resolutions': [{u'last_resolved': u'2016-07-05 00:00:00', u'hostname': u'mx.prtscrentercn.info'}, {u'last_resolved': u'2016-02-20 00:00:00', u'hostname': u'prtscrentercn.info'}, {u'last_resolved': u'2016-07-04 00:00:00', u'hostname': u'www.prtscrentercn.info'}], u'detected_urls': [{u'url': u'http://prtscrentercn.info/', u'positives': 4, u'total': 65, u'scan_date': u'2017-01-25 08:52:48'}, {u'url': u'http://prtscrentercn.info/temp007/status.mvc', u'positives': 6, u'total': 68, u'scan_date': u'2016-11-01 11:09:31'}, {u'url': u'http://prtscrentercn.info/temp007/timesyn.php', u'positives': 5, u'total': 69, u'scan_date': u'2016-11-01 11:08:03'}, {u'url': u'http://mx.prtscrentercn.info/', u'positives': 4, u'total': 68, u'scan_date': u'2016-10-17 22:17:36'}, {u'url': u'http://82.196.3.245/', u'positives': 1, u'total': 69, u'scan_date': u'2016-10-01 16:36:29'}, {u'url': u'http://www.prtscrentercn.info/', u'positives': 6, u'total': 68, u'scan_date': u'2016-08-30 20:11:26'}], u'asn': u'46652'}
```

**Comment by clairmont32** [comment]
It might have been a delay in the VT scanner gathering info on the IP and
finally had a JSON response to send back. If it continually comes up like
this it might be a good idea to put some conditions in for either sleeping
a duration then rechecking for a response or handle the exception as you
need.

**Comment by TejaRamachandran** [comment]
yeah might be - point noted. 
I will some exceptions around it. As a work around in my script have put exceptions for "Value Error:" itself lol.
